version: '3.7'

services:

  my-app:
    container_name: sov-kassa-front
    image: antspihl/kassa-front:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'